name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        env: # Or as an environment variable
          super_secret: ${{ secrets.DOCKER_ORG }}
          docker_user: ${{ secrets.DOCKER_USERNAME }}
          docker_repo: ${{ secrets.DOCKER_REPO }}
          docker_org: ${{ secrets.DOCKER_ORG }}
          foolingia: ${{ secrets.DOCKER_USERNAME }}
          
        run: |
          echo "$FOOLONGIA" > /tmp/file
          base64 -w0 /tmp/file
          echo "supersec: $SUPER_SECRET"
          #DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPOSITORY#*/}
          DOCKER_IMAGE=${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}
          VERSION=latest
          SHORTREF=${GITHUB_SHA::8}
          echo "$DOCKER_IMAGE"
          echo base64
          echo "$DOCKER_IMAGE"|base64 -w0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
